### ISSUE TITLE
Does it work with the MultiDrag plugin?

### ISSUE THREAD

**Issue by aurovrata** [SortableJS/jquery-sortablejs#2]
I am trying to use the [multidrag](https://github.com/SortableJS/Sortable/tree/master/plugins/MultiDrag) utils methods select and deselect

**Comment by depuits** [comment]
These should work together without a problem. You'd still have to mount the plugin like normal
```js
Sortable.mount(new MultiDrag());
```
and then you can pass the options in the jquery call like this
```js
$('#my-list').sortable({
	// SortableJS options go here
	// See: (https://github.com/SortableJS/Sortable#options)
	handle: '.handle',

	multiDrag: true, // Enable the plugin
	selectedClass: "sortable-selected", // Class name for selected item
	multiDragKey: null, // Key that must be down for items to be selected

	// Called when an item is selected
	onSelect: function(/**Event*/evt) {
		evt.item // The selected item
	},

	// Called when an item is deselected
	onDeselect: function(/**Event*/evt) {
		evt.item // The deselected item
	}
});
```

**Comment by aurovrata** [comment]
Thanks!  I got to work as per the instructions on the gituhub page, but I was actually wanting to know if instead of using 
`Sortable.utils.select(item)`
to programmatically select an item in the multidrag sortable list, there was a jquery equivalent.

**Comment by owen-m1** [comment]
@aurovrata there isn't this functionality yet, but I or @depuits could add it if he wants

**Comment by aurovrata** [comment]
no issues, I am happy to switch back to js for this functionality to work... I was just asking in case it existed.
