### ISSUE TITLE
Plugins in Jquery Version

### ISSUE THREAD

**Issue by hanleyhansen** [SortableJS/jquery-sortablejs#8]
I'm interested in plugins like multidrag but I'm using the jquery version. Is there any documentation on how to enable those plugins with jquery?

The following wiki instructs to mount the plugin:

https://github.com/SortableJS/Sortable/wiki/Dragging-Multiple-Items-in-Sortable

But when I attempt to do so I get an error: `MultiDrag is not defined`

**Comment by owen-m1** [comment]
@hanleyhansen It should work OOTB, just set `multiDrag: true` in the options

**Comment by hanleyhansen** [comment]
Thanks @owen-m1. Indeed it does, I had another conflict that was misleading me. All good now. Thanks for the prompt response.
